### ISSUE TITLE
Request: Mission search being case insensitive

### ISSUE THREAD

**Issue by EmosewaMC** [LUDevNet/lu-explorer#166]
Currently it is case sensitive, which is a bit restrictive considering the Objects search is not case sensitive.  Would be nice to have case insensitivity for this search too.

**Comment by Xiphoseer** [comment]
Underlying issue:

Mission search uses a plain old string includes on locale entries, while object search already uses a JS fulltext search library (which takes some time to build its index)

**Comment by Xiphoseer** [comment]
https://github.com/LUDevNet/lu-explorer/blob/main/src/app/missions/search/missions.component.ts#L32

**Comment by Xiphoseer** [comment]
Fixed via c0ac3f5b2f84c6b08fdb05067d9fc0b2802ed2a0
