### ISSUE TITLE
Move /skills behavior tree to lu-core-data

### ISSUE THREAD

**Issue by SimonNitzsche** [LUDevNet/lu-explorer#22]
https://xiphoseer.github.io/lu-explorer/skills/1412

**Comment by Xiphoseer** [comment]
That's this behavior: <https://lu-explorer.web.app/skills/behaviors/38607>

**Comment by Xiphoseer** [comment]
Another one: <https://lu-explorer.web.app/skills/1598>

**Comment by Xiphoseer** [comment]
> That's this behavior: https://lu-explorer.web.app/skills/behaviors/38607

FYI: This is the data that should be there: [tables/BehaviorParameter/38607](http://lu.lcdruniverse.org:10001/api/v0/tables/BehaviorParameter/38607) (this URL is subject to break)

**Comment by Xiphoseer** [comment]
@MasterTemple should be fixed now, can you check whether that's the case?

**Comment by Xiphoseer** [comment]
TODO: fix /skills view too
