### ISSUE TITLE
Some behavior types don't have their names displayed

### ISSUE THREAD

**Issue by lcdr** [LUDevNet/lu-explorer#83]
E.g. https://explorer.lu-dev.net/skills/behaviors/37846, https://explorer.lu-dev.net/skills/behaviors/37868, https://explorer.lu-dev.net/skills/behaviors/38481
All behavior template types are listed in BehaviorTemplateName in cdclient, we could add them easily
I assume this should ideally be moved from [behavior-detail-alt](https://github.com/Xiphoseer/lu-explorer/blob/main/src/app/skills/behavior-detail-alt/behavior-detail-alt.component.ts) to /defs/ ?

**Comment by Xiphoseer** [comment]
Yeah, I'd prefer defs over code and API over defs. I also have the full list of possible keys that should trigger `add_child` somewhere. Because the mostly contain `on` or `action` I don't think there are false positives if you check them for all nodes independent of ID.

**Comment by Xiphoseer** [comment]
Example: https://explorer.lu/skills/behaviors/20663/20676 ForceBehavior has `hit_action`, `hit_action_enemy` and `timeout_action` but none of them are added as child nodes

**Comment by lcdr** [comment]
That's a different issue though, as they're actually not displayed at all, instead of being nodes without a name.

**Comment by Xiphoseer** [comment]
> That's a different issue though, as they're actually not displayed at all, instead of being nodes without a name.

Yeah, I was treating this as one "data deriven behavior switch" issues because of

> I also have the full list of possible keys that should trigger add_child somewhere. Because the mostly contain on or action I don't think there are false positives if you check them for all nodes independent of ID.
